# Generated by Django 4.2.6 on 2023-11-30 10:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogs",
            name="description",
            field=models.CharField(default=None, max_length=500, null=True),
            preserve_default=False,
        ),
    ]
