# Generated by Django 4.2.6 on 2023-11-30 15:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogs", "0002_blogs_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogs",
            name="thumbnail_img",
            field=models.ImageField(
                blank=True, null=True, upload_to="blog_thumbnails/"
            ),
        ),
    ]
