# Generated by Django 4.2.6 on 2023-11-30 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("blogs", "0003_blogs_thumbnail_img"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogContentImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_images",
                    models.ImageField(
                        blank=True, null=True, upload_to="blog_content_images/"
                    ),
                ),
                (
                    "blog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="blogs.blogs"
                    ),
                ),
            ],
        ),
    ]
