# Generated by Django 4.2.6 on 2023-12-02 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("blogs", "0004_blogcontentimages"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogs",
            name="date_created",
            field=models.DateField(auto_created=True),
        ),
        migrations.AlterField(
            model_name="blogcontentimages",
            name="blog",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="content_images",
                to="blogs.blogs",
            ),
        ),
        migrations.AlterField(
            model_name="blogs",
            name="content",
            field=models.TextField(max_length=2450),
        ),
    ]
