# Generated by Django 4.2.6 on 2023-11-30 16:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogs", "0004_blogcontentimages"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogs",
            name="content",
            field=models.TextField(max_length=2450),
        ),
    ]
