# Generated by Django 4.2.6 on 2023-12-02 10:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogs", "0005_blogs_date_created_alter_blogcontentimages_blog_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogs",
            name="date_created",
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
