# Generated by Django 4.2.6 on 2023-12-01 18:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogs", "0006_blogs_date_created_alter_blogcontentimages_blog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogs",
            name="date_created",
            field=models.DateField(auto_created=True, null=True),
        ),
    ]
